"Sort list in ascending order" - Sort command
CS2103AUG2016-T11-C4/addressbook-level3 pull request #8
Opened 2016-10-06 08:31 UTC by snehasp13

2016-10-07 11:04 UTC, pyokagan requested changes
Fix these problems ASAP

2016-10-07 11:04 UTC, pyokagan commented on src/seedu/addressbook/commands/Sort.java
> +	        Collections.sort((List<ReadOnlyPerson>) allPersons);
`ReadOnlyPerson` needs to be [Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html) in order to be able to be sorted with `Collections.sort()`.

Doing a search on Google for `Java Collections.sort comparable` gives me these links:

* https://www.mkyong.com/java/java-object-sorting-example-comparable-and-comparator/
* https://docs.oracle.com/javase/tutorial/collections/interfaces/order.html

2016-10-07 11:04 UTC, pyokagan commented on src/seedu/addressbook/commands/Sort.java
> +
There is trailing whitespace on this line (and in many parts of this file). You can configure Eclipse to [strip trailing whitespace on save](http://stackoverflow.com/a/2618521)

2016-10-07 11:04 UTC, pyokagan commented on src/seedu/addressbook/commands/Sort.java
> +	        return new CommandResult(getMessageForPersonListShownSummary(allPersons), allPersons);
Tabs mixed with spaces in the indentation of this line. You need to make sure you only use spaces for indentation.

2016-10-08 00:24 UTC, snehasp13 commented
Changes made

2016-10-08 02:55 UTC, pyokagan commented
What changes were made? I don't see any changes.

2016-10-08 04:10 UTC, snehasp13 commented
Sent a new pull request with the edited code

On Sat, Oct 8, 2016 at 10:55 AM, Paul Tan <notifications@github.com> wrote:

> What changes were made? I don't see any changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CS2103AUG2016-T11-C4/addressbook-level3/pull/8#issuecomment-252398363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASY2q_ToNTyp0DnOANQDk2uPtrJI9xPkks5qxwY5gaJpZM4KPrYw>
> .
>

2016-12-09 12:41 UTC, closed without merging